name: serinus_openapi_example
description: "A voting application to test out Sut SSE on serinus and Globe"
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  acanthis: ^1.4.6
  drift: ^2.29.0
  serinus: ^2.0.1
  serinus_openapi: ^1.0.11
  serinus_serve_static: ^2.0.0
  sqlite3: ^2.9.4

dev_dependencies:
  serinus_lint: ^0.1.1
  drift_dev: ^2.29.0
  build_runner: ^2.10.2
